### ISSUE TITLE
Doesnt seem to work in arch/garuda linux?

### ISSUE THREAD

**Issue by t0int1337** [BrunoS3D/discord-enable-devtools#6]
I've tried adding `"DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true` and the command: `npx zx https://raw.githubusercontent.com/BrunoS3D/discord-enable-devtools/main/index.mjs`.
Both didnt work. I am pressing CTRL+SHIFT+I.
Running kernel: 6.4.10-zen2-1-zen

**Comment by rehhouari** [comment]
are you perhaps using the flatpak?

**Comment by t0int1337** [comment]
> are you perhaps using the flatpak?

i stopped using linux, its been a year... -.-

**Comment by brunos3d** [comment]
I guess this fixes the issue https://github.com/brunos3d/discord-enable-devtools/commit/33eac5111b67e9c7631b7961d291f9134b966993

Please let me know if the error persists and open a PR or an issue if possible.

Best regards
